version: 2

updates:

  - package-ecosystem: gomod
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    groups:
      go-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    groups:
      actions-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
